spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stu
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
mybatis:
  type-aliases-package: com.yu.entity
#  mapper-locations: classpath:mybatis-mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql